base_url = "https://tesujimath.org"
title = "tesujimath"
description = "Programming ponderations"
author = "Simon Guest"

compile_sass = true
build_search_index = true
generate_feeds = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
theme = "apollo"
menu = []
socials = []
