base_url = "https://tesujimath.org"
title = "tesujimath"
description = "Programming ponderations"
author = "Simon Guest"

theme = "apollo"
compile_sass = true
build_search_index = true
generate_feeds = true

taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
theme = "toggle"
socials = [
  { name = "github", url = "https://github.com/tesujimath", icon = "github" },
]

menu = [{ name = "about", url = "/pages/about", weight = 1 }]
